problem_name: "maximum_independent_set"
datasets:
  - type: "loaded"
    name: "dimacs"
feature_extractors:
  - name: "logarithm_of_nodes_and_edges"
  - name: "graph_connectivity"
  - name: "chromatic_number"
  - name: "graph_assortativity"
  - name: "approximate_mis"
  - name: "laplacian_eigenvalues"
  - name: "average_degree_connectivity"
  - name: "node_degree"
  - name: "clustering_coefficient"
  - name: "average_neighbor_degree"
  - name: "core_number"
solvers:
  - name: "GreedyCPPSolver"
  - name: "ReduMISSolver"
  - name: "OnlineMISSolver"
  - name: "WeightedBranchAndReduceSolver"
analyze:
  features:
    - log_number_of_nodes
    - log_number_of_edges
    - is_connected
    - chromatic_number
    - assortativity_coefficient
    - approximate_mis_size
    - log_largest_eigenvalue
    - log_second_smallest_eigenvalue
    - log_eigenvalue_ratio
    - average_degree_connectivity_mean
    - average_degree_connectivity_std_dev
    - average_degree_connectivity_min
    - average_degree_connectivity_max
    - average_degree_connectivity_log_abs_skew
    - average_degree_connectivity_skew_positive
    - average_degree_connectivity_log_kurtosis
    - average_degree_connectivity_const
    - node_degree_mean
    - node_degree_std_dev
    - node_degree_min
    - node_degree_max
    - node_degree_log_abs_skew
    - node_degree_skew_positive
    - node_degree_log_kurtosis
    - node_degree_const
    - clustering_coefficient_mean
    - clustering_coefficient_std_dev
    - clustering_coefficient_min
    - clustering_coefficient_max
    - clustering_coefficient_log_abs_skew
    - clustering_coefficient_skew_positive
    - clustering_coefficient_log_kurtosis
    - clustering_coefficient_const
    - average_neighbor_degree_mean
    - average_neighbor_degree_std_dev
    - average_neighbor_degree_min
    - average_neighbor_degree_max
    - average_neighbor_degree_log_abs_skew
    - average_neighbor_degree_skew_positive
    - average_neighbor_degree_log_kurtosis
    - average_neighbor_degree_const
    - core_number_mean
    - core_number_std_dev
    - core_number_min
    - core_number_max
    - core_number_log_abs_skew
    - core_number_skew_positive
    - core_number_log_kurtosis
    - core_number_const
