problem_name: "maximum_independent_set"
datasets:
  - type: "generated"
    generator: "test_creator"
feature_extractors:
  - name: "logarithm_of_nodes_and_edges"
    overwrite: true
  - name: "graph_connectivity"
  - name: "chromatic_number"
  - name: "graph_assortativity"
  - name: "approximate_mis"
  - name: "laplacian_eigenvalues"
  - name: "average_degree_connectivity"
  - name: "node_degree"
  - name: "clustering_coefficient"
  - name: "average_neighbor_degree"
  - name: "core_number"
solvers:
  - name: "GreedyCPPSolver"
    overwrite: true
  - name: "ReduMISSolver"
  - name: "OnlineMISSolver"
  - name: "WeightedBranchAndReduceSolver"
  - name: "WeightedLocalSearchSolver"
